src/p2p/transport.rs
=> We prefer mplex over yamux. 

README.md
Looked into using [skeptic](https://crates.io/crates/skeptic) but it apparently compiles the README.md code with by calling `rustc` directly so we end up with nightly ipfs being linked against readme testcase compiled with stable, which unsurpringly does not work.
Perhaps it could work still work with travis without any other rustc installed?
=> chore sync readme with examples/readme.rs

.travis.yml, README.md, examples/client1.rs, examples/client2.rs, examples/ipfs_bitswap_test.rs, examples/ipfs_ipns_test.rs, examples/readme.rs, src/bitswap/behaviour.rs, src/bitswap/bitswap_pb.rs, src/bitswap/ledger.rs, src/bitswap/protocol.rs, src/bitswap/strategy.rs, src/config.rs, src/ipld/formats/cbor.rs, src/ipld/formats/pb/dag_pb.rs, src/ipld/formats/pb/mod.rs, src/ipld/ipld.rs, src/ipld/mod.rs, src/ipns/dns.rs, src/ipns/entry.rs, src/ipns/ipns_pb.rs, src/lib.rs, src/p2p/behaviour.rs, src/path/mod.rs, src/repo/mod.rs
Clear out clippy warnings. I'll squash this before merging but let's see if clippy on travis requires something more.
EDIT: ok to merge, pls squash. I do not want to squash as that would probably lose the few comments I made.
=> Clippy run

src/bitswap/bitswap_pb.proto, src/bitswap/ledger.rs
Also fix quite embarrassing bug in the proto serialization
=> Add new bitswap protocol from go-ipfs

README.md
I think this looks great 😁 @aphelionz
=> docs: use the Rust IPFS logo

.github/workflows/ci.yml
I noticed that CI was running twice if I created a branch and made a PR. How do we feel about this new config?
=> CI running on push to master and PRs

README.md
To comply with https://www.rust-lang.org/policies/media-guide
=> Adding Trademark to README.md

README.md
Working from https://github.com/RichardLitt/standard-readme/blob/master/spec.md
#61
=> Standard Readme

http/src/v0/version.rs
incl. additional fields for rust-ipfs-api.
=> fix: version to contain all fields for tests

examples/ipfs_bitswap_test.rs
First attempt at first example related to #196
=> Adjust ipfs_bitswap_test example

http/src/v0/swarm.rs
this follows the lead of js-ipfs with the "n/a" fallback response by default.
Related: #178 and the transient failures we are getting.
=> fix: return "n/a" in verbose swarm peers response

README.md
This PR adds dependencies to the README.md
=> Updating Install instructions

bitswap/src/protocol.rs, http/src/main.rs, http/src/v0/pubsub.rs, src/lib.rs, src/repo/fs.rs, src/repo/mem.rs, tests/pubsub.rs, unixfs/src/file/visit.rs, unixfs/src/pb/merkledag.rs, unixfs/src/pb/unixfs.rs
Assorted drive-by cleanups and small refactorings; individual commits describe the specific changes.
=> A round of cleanups

http/src/v0/block.rs, http/src/v0/dag.rs, http/src/v0/pubsub.rs, http/src/v0/refs/path.rs
Individual commits describe specific changes.
=> A handful of perf/brevity bits and bobs

README.md
=> Adding new dependency to README

http/src/v0/block.rs, http/src/v0/dag.rs
boxing reallocates and cid generation can fail. also added comments.
Follow-up on https://github.com/rs-ipfs/rust-ipfs/pull/230#discussion_r452031610
=> refactor: delay boxing after cid generation

http/src/v0.rs, http/src/v0/pubsub.rs, http/src/v0/root_files.rs, http/src/v0/root_files/add.rs, unixfs/src/file/adder.rs
Adds initial file adding through `/add` interface. Does very little of else.
=> Initial file add

Cargo.lock, http/Cargo.toml, http/src/v0/pubsub.rs, src/p2p/swarm.rs, tests/connect_two.rs, tests/multiple_listening_addresses.rs
=> Use async macro for tests

tests/connect_two.rs
gha windows was stuck on this. it's not nice since we cannot see any
testing output before the run is cancelled.
=> fix: add timeouts to connect_two tests

http/src/v0/swarm.rs, src/p2p/swarm.rs, tests/connect_two.rs
Also add related tests and tweak `connect_two` tests a bit.
=> Allow connecting using multiaddr/p2p/peerid

tests/wantlist_and_cancellation.rs
This might help the rare errors thrown by the `bounded_retry` test function that might be a bit too busy at times.
Also, reduce the delay for `timeout(duration, pending::<()>())` calls and increase the one for `bounded_retry` ones.
=> make the retrying loop in wantlist_cancellation less busy

CONTRIBUTING.md
I think the build time should become apparent right away for anyone trying to develop, at least when GHA tries it.
=> doc: update contributing, minimal patches

src/lib.rs
Apparently `Span::in_scope` is just:
```
pub fn in_scope<F: FnOnce() -> T, T>(&self, f: F) -> T {
let _enter = self.enter();
f()
}
```
and `Span::enter` is a no-no in `async` contexts.
=> Use instrument instead of in_scope in lib

.github/workflows/ci.yml
according to commits there have been some changes related to caching,
unable to determine if they actually fix anything.
=> ci: update run-vcpkg (get windows caching)

http/src/v0/refs.rs
Really minor fix on top of current staging (#332): fix how the visited hashset is used. I don't know why I always write it this way, I guess it's helpful in dijkstra implementations to check the map for distance but this is BFS.
- there actually is a test case for unique
Not applicable:
=> fix(http/refs): check for unique nodes before queueing

src/p2p/addr.rs, src/p2p/swarm.rs
It appears that the `unwrap` there was a bit too liberal - try to mitigate it.
=> Less panic-ky inject_addr_reach_failure

conformance/patches/find_provs.patch, conformance/test/index.js, http/src/v0/dht.rs, src/lib.rs, src/p2p/behaviour.rs, tests/kademlia.rs
I think I'll cut the PR at this point already, as I'm seeing some issues related to the skipped tests that could make it grow bigger.
Current status: `12 passing, 8 skipped`.
=> Run (and pass) most of the dht conformance tests

src/lib.rs, tests/kademlia.rs
Not much to add here - the tests were mostly refactored and some got improved as a side effect.
=> Better DHT docs and tests

Cargo.lock, Cargo.toml, bitswap/Cargo.toml
A routine round of dependency updates.
=> Update libp2p to 0.28, cargo update the other deps

Cargo.lock, src/lib.rs, tests/bitswap.rs, tests/common/mod.rs, tests/exchange_block.rs, tests/kademlia.rs, tests/pubsub.rs
No functional changes, just quality of life / developer experience ones plus a small dependency update.
As always, the commits describe the specific changes.
=> Tidy up some dependencies and tests

README.md
Self-explanatory: just a few updates to the README, plus the removal of old issue links.
=> update README, remove old links

src/p2p/behaviour.rs
Return explicit subscription errors on some of the more user-facing DHT requests, namely `Bootstrap`, `StartProviding` and `PutRecord`; `Kademlia` errors for those are currently only logged and `KadResult::Complete` is returned, potentially concealing issues.
=> return errors for some extra DHT issues

README.md
=> Removing MRH.io from the README

src/p2p/addr.rs, src/p2p/mod.rs, src/p2p/swarm.rs, src/path.rs
This PR goes some way towards improving the documentation of public methods as discussed in #197.
=> Improve documentation of public methods 

http/src/v0.rs
This PR supercedes #422 as bors couldn't handle the "PR is from removed repository" case, so this is made from a branch which has only the same commit as the previous PR. PR uses the balanced tree approach from warp issue for further compilation time speedups. The commit hash differs because I apparently applied it per githubs instructions on top of different commit than the original seems to be, with different metadata.
Closes #422.
=> Further reduction of ipfs-http compilation times, take two

http/src/v0/refs/format.rs, http/src/v0/root_files/add.rs, src/ipns/dnslink.rs, src/lib.rs, src/p2p/behaviour.rs, unixfs/src/dir/builder/iter.rs
=> Clippy lints in 1.48

CONTRIBUTING.md, README.md
unlink the channel as we haven't had much presence there in the recent months. as an alternative, list issues.
=> docs: unlink matrix and discord, issues for questions
