src/bitswap/protocol.rs

We had troubles reading incomming messages, they were just being dropped it seemed. Turns out our buffer reading length was quite long enough, though the specification doesn't actually state, what size a bitswap message can have. This PR sets the limit to the limit I found in the js-ipfs-bitswap implementation: 524288 bytes.

Increase Buffersize for bitswap messages

---

Cargo.lock
Cargo.toml
src/config.rs
src/ipns/dns.rs
src/repo/mod.rs

With an RSA key and `go-ipfs` 0.4.22 I was able to provide the `"block-want\n"` from go-ipfs and connect go-ipfs with rust-ipfs as a bootstrap peer. The big upgrade left the output a bit bad: it no longer prints the listening address and this needs to be fetched at `IpfsFuture` which I did not add here.
`ring` does not have RSA key generation yet but if you want to test this with an rsa key you can follow [the instructions in libp2p docs](https://docs.rs/libp2p-core/0.13.1/src/libp2p_core/identity.rs.html#38) and create a config.json like (from the test case), use it with `IPFS_TEST_CONFIG` environment variable.
```json
{"rsa_pkcs8_filename":"foobar.pk8","bootstrap":[]}
```
This includes an update to the deps to have the `aes-ctr` fix I am working on `RustCrypto/stream-ciphers`. The code …

Get bitswap test against go-ipfs working

---

.travis.yml
rust-toolchain
src/error.rs
src/ipld/formats/pb/mod.rs
src/ipld/ipld.rs
src/lib.rs
src/path/mod.rs

Sorry for removing my original comment to the relevant issue #36 where I was asking about using `void::Void` to remove the `try_trait` feature.
In this PR I've added the unit struct, `TryError`, to `src/error.rs` to replace all cases of `NoneError`.
All tests appear to succeed when executing `cargo test` from stable, but I was unsure how to test the example files.

Migrating to stable: Replaced NoneError with TryError

---

Cargo.lock
Cargo.toml
README.md
examples/client1.rs
examples/client2.rs
examples/ipfs_bitswap_test.rs
examples/ipfs_ipns_test.rs
examples/readme.rs
src/bitswap/behaviour.rs
src/bitswap/protocol.rs
src/bitswap/strategy.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs

Update rust-libp2p dep to libp2p v0.14.0-alpha.1 (324f0dc326cfdbc2d40d1e134a5734513d809b4c)
and make it compile. Not really sure if everything works, but I think this is a good start.

Switch to rust-libp2p version with stable futures

---

Cargo.lock
Cargo.toml
src/bitswap/protocol.rs
src/p2p/behaviour.rs

This solves a few issues:
-peer id inlining
-private swarms

Use rust-libp2p master from 2020-02-05

---

Cargo.toml
LICENSE-APACHE
LICENSE-MIT
README.md

I'll be following up with PRs to other repos. Changes:
* Cargo.toml: copied from https://github.com/rust-lang/cargo/blob/master/Cargo.toml#L8
* LICENSE-MIT, LICENSE-APACHE copied from cargo tree few minutes ago
* README.md: written by myself
I'll still need to check that the readme links work as I didn't copy those for some reason :)
I am requesting reviews from all committers who I was able to find with `git log --format="%aN <%aE>"| sort -u` except for @austinsheep ... Unsure why I am not able to add you, but please review and approve:
Please add a comment like if you approve (as noted by [vmx](https://github.com/ipfs-rust/rust-ipfs/pull/50#issuecomment-589028445)):
> I license past and future contributions under the dual MIT/Apache-2.0 license, allowing licensees to choose either at …

switch license from isc to mit/apl2.0

---

Cargo.lock

I rebased my PR branch in order to get a new CI run on stream-ciphers, and forgot Cargo.lock was locked into the now-missing commit. This bumps the commit.

fix rebased patched dep

---

.github/workflows/ci.yml

with the https://github.com/ipfs-rust/rust-ipfs/pull/85 there were first some spurious failures on windows (probably transient gh infra issues) and later we noticed that the checkout action on lint-rust and readme-doctest was failing.
I noticed the checkout action on the failing jobs were using an older version of the failing action than the matrix action which succeeded. tried to upgrade that and it worked, didn't look further.

fix: ci stop using actions/checkout@v1

---

Cargo.lock
http/Cargo.toml
http/build.rs
http/src/main.rs

Closes #78. Nothing special. I only added here, but was thinking the http module to could move into structure similar to `v0::version::{Query, Response, version}` or `v0::id::{Response, id};`  instead of appending everything to a single endless main.rs :)

Impl version http endpoint

---

.github/workflows/ci.yml
Cargo.lock
http/Cargo.toml
http/build.rs
http/src/config.rs
http/src/keys.proto
http/src/lib.rs
http/src/main.rs
http/src/v0.rs
http/src/v0/version.rs
src/config.rs
src/lib.rs
src/p2p/mod.rs

Sorry for the refactoring with the http being here as well, I created a config module with configuration file handling there. The `rsa` keygen and following import/export thing was a lot more difficult than I thought.
I made some questionable changes to `ipfs::config` as well, I removed it from the `ifps::IpfsOptions`. I made this because looking back at the `ipfs::config::KeyMaterial` it seems like a bad idea to extend it with `Pkcs8Buffer` or something similar, I am not so sure if the mutability through `Option`s makes a lot of sense. If this solution feels worse I can present the `KeyMaterial` extension as well. I also thought that the "library initialization through configuration file" might not be so important use case after all, as most likely you'd like to bring your application …

RSA keygen in preparation to asking /id from ipfs

---

examples/client1.rs
examples/client2.rs
examples/ipfs_bitswap_test.rs
examples/ipfs_ipns_test.rs
http/src/config.rs
http/src/main.rs
http/src/v0.rs
http/src/v0/id.rs
src/lib.rs
src/repo/mod.rs

1. fix back https://github.com/ipfs-rust/rust-ipfs/pull/99#discussion_r392204494
2. do a simple query for swarm for `/id` local part
Same as with any `warp::query` at the moment, the error handling needs to be improved and get away from the `Box<dyn warp::Reply>` kind of handling. Unsure yet what'd entail.
Communication with the swarm is done through `IpfsEvent` extending which allows us to get a oneshot sender over to the background task to report back. This is handled privately so we are not at least linking this to the public api. Currently returns 501 not implemented for `/id?arg=another_peerid`.

Expose actual local /id

---

.github/workflows/ci.yml
Cargo.lock
http/Cargo.toml
http/README.md
http/src/main.rs

Renames the `rust-ipfs-http` into `ipfs-http`, even though we might want to hold off publishing the crate until someone decides to need it. Also written a small README on the purpose of `ipfs-http`.
This will cause a small conflict with my other two PR's but I can take care of that.

Rename http crate and create it a readme

---

http/src/main.rs

This is a leftover from PR #103.

fix: both crate names were wrong by default RUST_LOG

---

src/lib.rs
src/p2p/swarm.rs
tests/connect_two.rs

~The test case hangs for unknown reason.~
The test hung initially because a pending `NetworkBehaviourAction` was placed in the queue to be popped on next poll but the waker was never notified that poll needed to be called again.

Add connect integration test

---

src/lib.rs
src/subscription.rs

The spawning is not needed as the future can be returned as is. I think it's beneficial to limit the concurrent number of things to "incoming concurrency" if at all possible so that the system remains debuggable.
I think the error path could be simplified, not sure why not just make it an anyhow::Error near the source with `format_err!`...?

refactor: remove needless spawning

---

http/src/v0.rs

IpfsOptions::<T>::default() reads from disk, which I had forgotten when writing the test case. Not sure if this is the cause but lets see.

fix: stop reading common config during tests

---

src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/p2p/pubsub.rs
src/p2p/swarm.rs
tests/pubsub.rs

First part of #76.
Implemented by wrapping floodsub. Played around with the semantics and currently there might be too many operations; the unsubscribe might be too much. Also the method names are prefixed with `Ipfs::pubsub_` which hopefully will spark new better ideas. For naming, perhaps just removing the method name prefix would be fine.
Initially thought that maybe subscribe and unsubscribe are both needed but while testing realized it's quite strange if the unsubscription happens with on next message (or never) after drop, so I created a unsubscribe on drop wrapper for the sender. The channels used are currently all unbounded.
I initially thought that publishing messages might need to be part of the subscription, but looking at floodsubs implementation whether or not there exists a …

Add pubsub api

---

Cargo.lock
Cargo.toml
http/Cargo.toml
http/src/v0.rs
http/src/v0/pubsub.rs
http/src/v0/support.rs
src/lib.rs
src/p2p/mod.rs
src/p2p/pubsub.rs
tests/pubsub.rs

Adds the `/api/v0/pubsub` endpoints. Passing the conformance tests requires a modified libp2p-floodsub which I haven't yet pushed. The required functionality is getting the locally sent messages as if they were received over the swarm published over to subscriber(s).
This depends on #118 so creating this as a draft.
Things still to do:
The latter has not been done. I am currently more interested in lowering the broadcast channel size to less than what the conformance tests use by getting some backpressure in, but that'll have to be later.

Add pubsub http

---

Cargo.lock
src/p2p/pubsub.rs
tests/pubsub.rs

Also including a possibly leftover update to Cargo.lock from the #123 ... I think?Perhaps we should have a CI check that the lock file is unchanged after build?

Fix flaky pubsub test

---

http/src/main.rs
src/lib.rs
src/repo/mod.rs
src/subscription.rs

This fixes the deadlock found when working on the WIP #126 code.
I saw you already refactored these subscription registries out and replaced them with oneshot channels. I think that is a good idea but didn't investigate it too deeply, as they'll handle dropping and cancelling issue better. 
I'll follow up this with #126 new features on top of this.

Fix subscription deadlock

---

Cargo.lock
bitswap/src/behaviour.rs
bitswap/src/block.rs
bitswap/src/ledger.rs
bitswap/src/lib.rs
bitswap/src/strategy.rs
http/Cargo.toml
http/src/main.rs
http/src/v0.rs
http/src/v0/bitswap.rs
http/src/v0/block.rs
http/src/v0/support.rs
src/dag.rs
src/lib.rs
src/p2p/behaviour.rs
src/repo/fs.rs
src/repo/mem.rs
src/repo/mod.rs
tests/exchange_block.rs

Depends on #130 and takes the functionality developed on #126 (`/block` and `/bitswap`) but without the major refactoring. In the end I was surprised that the `tests/block_exchange.rs` worked. I tried to add `Co-authored-by:` headers to the commits which took the code @dvc94ch had published.
I had missed the changes made to bitswap on #99 which I merged in hurry so it took some fixing. I think the idea of removing BitswapStore altogether and replacing it and all the spawns by BehaviourEvent is the right way to go. I think it'll be an easier refactoring on top of this now that the `exchange_block` test should be working.
New thing here to allow accounting for duplicate blocks is the `put_block(...) -> Result<(Cid, BlockPut), _>` where `BlockPut` is a simple enum representing whether or not …

Add bitswap block apis

---

src/lib.rs

Fixes the three flaky tests and tries to make sure no new similarly flaky tests can be introduced, document the thread unsafety.
I didn't go and start using a mutex or anything like that because the use of filesystem is always prone to races.

Fix more flaky tests

---

http/src/v0.rs
http/src/v0/refs.rs
src/lib.rs
src/repo/fs.rs
src/repo/mem.rs
src/repo/mod.rs

This PR adds a conformance-passing `/api/v0/refs/local` endpoint.
I added a `list` function to the `BlockStore` trait.
TODO:
Note that this includes the work from #137 and will be rebased

Refs local endpoint

---

Cargo.lock
Cargo.toml

This PR pins the domain crate to a specific revision. domain has moved on quite a bit and when this 
I tried to use `rust-ipfs` as a crate in another project, I got this error: 
```
error: failed to select a version for `domain`.
... required by package `ipfs v0.1.0 (https://github.com/ipfs-rust/rust-ipfs#89e3f7c5)`
...
the package `ipfs` depends on `domain`, with features: `resolv` but `domain` does not have these features.
failed to select a version for `domain` which could resolve this conflict
```
I'd love to get it updated to at least `0.5.0` but I don't know exactly how much work that entails. It does indeed raise the importance of #75

fix: pin domain to specific revision

---

.github/workflows/ci.yml
examples/examples/ipfs_bitswap_test.rs
http/src/v0/block.rs
http/src/v0/dag.rs
http/src/v0/refs.rs
src/lib.rs
tests/exchange_block.rs

* refactor away unnecessary `&mut self` from ipfs::Ipfs blockstore calls
* enable building of examples and tests in the same phase
* require `Cargo.lock` to be up to date `cargo build --locked`
This is split and extended from #147, where I'll be dropping the first commit soon-ish.

Refactor muts away, enhance ci builds

---

Cargo.lock
Cargo.toml
examples/Cargo.toml
http/Cargo.toml
http/src/lib.rs
http/src/main.rs
http/src/v0.rs
http/src/v0/refs.rs
http/src/v0/refs/format.rs
http/src/v0/refs/options.rs
http/src/v0/refs/path.rs
http/src/v0/refs/support.rs
http/src/v0/refs/unshared.rs
http/src/v0/support.rs

Builds on #137 and later #155
TODO:
I'll be rebasing and probably separating the needless `mut` removal, which is probably a clippy issue why that wasn't picked up. Apparently the clippy or the compiler don't support linting on this at the moment.

Add refs endpoint

---

.github/workflows/ci.yml
http/src/v0/block.rs
http/src/v0/dag.rs
src/p2p/swarm.rs
src/repo/fs.rs
src/repo/mem.rs
src/subscription.rs
tests/pubsub.rs

I noticed we were running clippy only for the root crate in the workspace, excluding it's tests. This starts running it with `--workspace --examples --tests`.
I needed to allow that `clippy::mutable_key_type` for the tests. I don't think there's a way to fix the tests to work without ... Perhaps with rendering everything to string but perhaps that doesn't make much sense.

CI: Run clippy on whole workspace

---

http/src/v0/dag.rs

This gets us to pass all conformance tests for `dag.put`.
This will now conflict after #156 but that'll be easy to resolve.

fix: use correct query param name

---

http/src/v0/refs/format.rs
http/src/v0/refs/path.rs

it is quite difficult to remember the --workspace --tests parameters.. I messed up by merging first 147, then not rebuilding completly before merging the following two. bors would be nice :)

refactor: remove clippy warnings

---

http/src/v0.rs
http/src/v0/dag.rs
http/src/v0/refs.rs
http/src/v0/refs/path.rs
src/lib.rs
src/repo/mod.rs

The first commit is a bugfix, should probably make that into a interface-http-core test case.
TODO:

Add /dag/resolve endpoint

---

http/src/v0/block.rs
http/src/v0/refs.rs

This PR fixes two minor bugs found while doing final 1.2 conformance testing:
1. ~Refs local wants the results to be returned as `Qm***` multihashes~
2. Block rm had a minor typo-related bug, switched two lines.
Edit: only the block rm fix now

fix: minor block/rm bug

---

http/src/v0.rs

by boxing the filters on debug builds. Note: the 50% is for me in clean builds, down from 5 minutes to about 2 minutes. Incremental builds are less than 30s depending on the change.

fix: decrease ipfs-http compilation times 50%

---

http/src/v0/support/unshared.rs

not exactly sure how critical this is, but all of the thinking which was done for "is this Stream impl ok" was based on the assumption that the Unshared value was Send, as it was but this was never added as a bound.

fix: add T: Send bound for Unshared<T>

---

src/p2p/swarm.rs
tests/multiple_listening_addresses.rs

This one test is failing consistently in #176. I separated it to be able to cleanup the commits in #176 better.
The macosx segfault does not seem to be related to possibly anything.

fix: flaky adding two same ip ephemerals

---

.github/workflows/ci.yml

also attempt to cache llvm as well, but apparently that does not work and chocolatey ends up downloading the same 160MB either way.
after first successful build this should be able to cache the 15min openssl build away.
Merging when I get a passing build, unless there are objections.

fix: cache openssl build on windows

---

README.md

This PR adds an "Alternatives" section to the README, to raise awareness of other implementations.

Alternatives section in README

---

.gitignore

Besides /target, there are many target folders inside examples. Please change /target to target so that those build files can be ignored by github

Remove the / before target can help ignore build files

---

tests/exchange_block.rs

this has been hanging on CI sometimes, 10s is more than enough for this operation under the heaviest load.

test: add timeout to exchange_block

---

Cargo.lock
http/Cargo.toml
http/src/v0/root_files.rs

If the test fails to delete once, it'll persist the failure. Using tempfile::tempdir should give us a cleaned up after temporary directory.

fix test using non-unique tempfile

---

.github/workflows/ci.yml

If this works it should shave some 4min of the runtime. Still unsure how to upgrade the openssl later. Probably by doing a run with the cache steps disabled and later enabled?

ci: skip llvm install if openssl is cached on windows

---

unixfs/src/walk.rs

This was forgotten on the unixfs walk. While even without these there would not had been a warning on never created `Error::File` file variant, unsure why not. I guess this is why one shouldn't be forcing anyone to review +3k PRs :)
I did a pass and there are no other such allow's left. The remaining (outside of unixfs) are pretty much meant to be there.

unixfs: Remove forgotten lint suppression

---

Cargo.lock
unixfs/CHANGELOG.md
unixfs/Cargo.toml
unixfs/README.md

The ipfs-unixfs crate could go out while we still have git deps on the main crate.
This PR adds Cargo.toml metadata, initial CHANGELOG for the subcrate, README changes, license mentioning. Also drops the `tar` dependency which I had forgotten and uses simpler version requirement for `either` as I can't come up with a reason to be `>=1.5.3`.
Once merged, I'll tag the merge commit as `ipfs-unixfs/v0.0.1`.

Prepare initial ipfs-unixfs release

---

.github/workflows/ci.yml

With core dumps we should be able to see which causes the sigsegv and sigabrt. They of course don't seem to happen anymore, but #187 has links to past logs.

ci: macos core dump collection

---

unixfs/CHANGELOG.md
unixfs/src/file.rs
unixfs/src/file/reader.rs

Fixes #202. Includes minor touchup to also remove further unused parts.

ipfs-unixfs: Hide FileReader

---

bitswap/src/behaviour.rs
bitswap/src/ledger.rs
bitswap/src/protocol.rs

It seems to me that we don't need `ledger::Message` to be generic; I get the point behind the tag, but IMO its handling is simple enough to not require it at all.
Originally I also removed what vscode suggested to be an unused import, but my trust in it seems to have been misplaced :laughing:.

cleanups: simplify ledger::Message

---

bitswap/src/behaviour.rs
src/dag.rs
src/ipns/mod.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/repo/mod.rs
src/unixfs/mod.rs

This allows us to pass the central `Ipfs` object around when needed, improving what we can do within its child objects. In addition:
- `impl Default for Bitswap` (now possible)
- replace `Arc<Repo>` with a reference to `Ipfs` in `IpldDag` and `Ipns`, which are now created on-the-fly when needed
- poll for `BitswapEvent`s using `NetworkBehaviourEventProcess`
- un`Arc` the `Repo`

Arc-ify the Ipfs struct

---

bitswap/src/protocol.rs
http/src/v0/block.rs
src/repo/fs.rs
src/repo/mem.rs
src/subscription.rs

~~Builds on https://github.com/rs-ipfs/rust-ipfs/pull/226, only the last 5 commits are new.~~
The commit messages describe the specific changes, of which the following are the most interesting:
- don't clone the `Subscription`'s result unless it's ready
- enum-ify the `Subscription` object

Assorted improvements, continued

---

Cargo.lock
http/Cargo.toml
http/src/v0/block.rs
http/src/v0/dag.rs
http/src/v0/support.rs
http/src/v0/support/body.rs

Supercedes #225 to cover `dag/put`. I'll close the earlier and keep this as a draft while the temp git dependency is in place.
This allows accepting multipart bodies without Content-Length header by using mpart-async. Uploads are limited to 1MB.
As minor fixes this includes checking `dag/put?input-enc=raw` as we don't support any other input-enc at the moment (rust-ipld could read dag-json, this was implemented during phase1 already).
As more minor fixes this includes transformation of LengthRequired rejection to "Missing header: content-length" instead of "UNHANDLED REJECTION".
Fix is needed for #228.

Streaming multiparts at block/put and dag/put

---

Cargo.lock
http/Cargo.toml
http/src/v0/block.rs
http/src/v0/dag.rs
http/src/v0/pubsub.rs
http/src/v0/support.rs
http/src/v0/support/body.rs

This was seen originally but at least it seemed some months ago that there wasn't a way to process multiparts streaming. Luckily the older js-ipfs-http-client puts the message in query. Later versions related to #228 use multipart bodies, but the topic is still a query argument.
Depends on #230.
* Adds test for the older query part message parsing
* Uses `&'static str` instead of `&'static [u8]` (fixes error messages)
The latest version should leave us failing only the conformance tests related to:
* pinning
* `?timeout=<not sure what unit>`
* refs
* cat
* get
* block/get
* dag/get
* wantlist
This is:
```
146 passing (3m)
21 pending
8 failing
```

Streaming multiparts: pubsub

---

bitswap/src/ledger.rs
bitswap/src/protocol.rs
src/lib.rs
src/p2p/behaviour.rs
src/repo/mod.rs
src/subscription.rs

This can be achieved by taking advantage of the `RepoEvent::ProvideBlock` that always follows a finished subscription.
In addition there are a few other self-contained drive-by changes, described in their respective commit messages.

Finishing subscriptions should update the wantlist

---

Cargo.lock
http/Cargo.toml
http/src/v0/block.rs
http/src/v0/dag.rs
http/src/v0/refs.rs
http/src/v0/refs/options.rs
http/src/v0/root_files.rs
http/src/v0/support.rs
http/src/v0/support/option_parsing.rs
http/src/v0/support/serdesupport.rs
http/src/v0/support/timeout.rs

Related to #228, this adds timeout handling to:
* `block/get`
* `dag/resolve`
* `refs` (partial)
* `cat` (partial)
* `get` (partial)
Partial means only the initial step of at minimum path walking has the timeout. We cannot yet return errors from streamed bodies because of the lack of `Trailer` support in hyper, so no "request timeout" is enforced once we get to streaming the body.

Add http timeouts

---

Cargo.lock
http/Cargo.toml

0.4.1 with fix_7 was released just now.

chore: use released mpart-async

---

bitswap/src/behaviour.rs
bitswap/src/ledger.rs
bitswap/src/protocol.rs
http/src/v0/support.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/swarm.rs
src/repo/mod.rs
src/subscription.rs
tests/wantlist_and_cancellation.rs

I'd have split these changes into more commits, but a lot has changed in the meantime - this was not a trivial thing to do right, that's for sure :dizzy_face:.
~~In any case, it is _almost_ done: the last thing left is to make sure the `Cid` in the wantlist and the subscription list matches, as now we upgrade the latter, which makes the test loop indefinitely if the `Cid` differs between versions.~~ deferred
~~partially solves https://github.com/rs-ipfs/rust-ipfs/issues/236; the functionality is there, but the JS conformance test doesn't pass - might need patching~~
actually closes https://github.com/rs-ipfs/rust-ipfs/issues/236

cancel Blocks from the wantlist when all their Subscriptions die

---

src/repo/mod.rs
src/subscription.rs

Removes the previous linear search in `finish_subscription` and the now-unneeded `Request` object.
I'm pretty sure there is a little bit of `RequestKind` cloning that can be removed, but that's minor in comparison and can be improved upon later.

optimize the SubsctiptionRegistry

---

tests/multiple_listening_addresses.rs

not a complete solution to the issue but no need to have these nagging unnecessary test failures when we have the issue #194 for the problem class.

test: ignore flaky test

---

.github/workflows/ci.yml
conformance/.gitignore
conformance/README.md
conformance/http
conformance/package-lock.json
conformance/package.json
conformance/patches/0001-fix-allow-either-cidv-0-1-in-refs-local-test.patch
conformance/rust.sh
conformance/setup.sh
conformance/test/index.js

Having discussed this with @aphelionz and @ljedrz we couldn't come up a single good reason to keep this in a separate repository. History is not brought in as that would enlarge rust-ipfs repository by 30MB.

Merge ipfs-rust-conformance

---

unixfs/src/file/adder.rs

Rather a big rewrite on the balanced tree builder. The failing test case showed that compression happened too eagerly. This meant adjusting the `<` to `<=` in the two `work <= self.branching_factor` conditions, and making the "compression" a loop.
After pondering this a while, I wrote the loop internals to be "inplace mutating" instead of "drain" and "insert", which moved complexity a bit around. Also refactored the N argument fn out.
Fixes #242.

Fix full link blocks

---

.github/workflows/ci.yml
conformance/package-lock.json
conformance/package.json
conformance/patches/0001-fix-allow-either-cidv-0-1-in-refs-local-test.patch
conformance/patches/await_subprocess.patch
conformance/setup.sh
conformance/test/index.js
http/src/main.rs

This should add the diagnostic, but not hang the builds. Lets see how lucky we get. This is following the test win/mac failures on #249 and #250.
In this PR:
- why-is-node-running triggered 1min after interface-ipfs-core tests complete (so visible only when stuck)
- ipfsd-ctl patched to always await for subprocesses (this seems healthy either way)
- tests ignored:
- miscellanious.stop for surely causing the hang
- add from invalid url for likely causing a hang (DNSWRAP)
Need to investigate further what is causing the hangs with the stop -- it seemed like a deadlock. Not sure what happens with the DNSWRAP; perhaps the invalid url is good enough, but our rejection causes it to be "forgotten" and as such it seems to linger as it's completion is never checked once we fail the url add.

Fix hanging interface-ipfs-core tests

---

src/lib.rs
src/p2p/behaviour.rs
src/repo/mod.rs
src/subscription.rs
tests/wantlist_and_cancellation.rs

This allows us not to call the `async` counterpart (that spawns a potentially long-lasting `SubscriptionFuture`) when being asked for a `Cid` by other peers.
In addition, expand the `wantlist_cancellation` test a little bit - these changes don't affect it after all, but the extra checks are useful.

introduce a local get_block_now functionality

---

.github/workflows/ci.yml
conformance/http
conformance/setup.sh

This PR removes the symlink from source control, and adds some lines to validate and create the symlink to `conformance/setup.sh`. It also updates CI to build the project _before_ trying to create the symlink, as per the warning in `setup.sh`
The reasoning behind this is for GitHub Pages + Jekyll, which will break upon encountering a symlink that doesn't resolve properly in the repo.

Migrating http symlink creation to conformance/setup.sh + CI Update

---

bitswap/src/behaviour.rs
bitswap/src/ledger.rs
src/p2p/behaviour.rs
src/repo/mod.rs

The previous version relied on block_on for the block reads, lets see if this still timeouts on `exchange_block`.
This changes the `queued_blocks` to be `UnboundedSender<(PeerId, Block)>` instead of `Arc<Mutex<Vec<(PeerId, Block)>>>`. An alternative would had been to store the waker but we concluded the channel would be more appropriate.

Fix bitswap ready block wakeup

---

.github/workflows/ci.yml

bors should only fast forward or reset the master to HEAD of staging at the end of each run, so if there is a credit system on GH we are just wasting those credits on each merged PR.
if nothing else, this should be more energy efficient :) if bors fast forwarded something the commit should have the status badge.

ci: stop building pushes to master

---

http/src/main.rs
http/src/v0.rs
http/src/v0/refs.rs
http/src/v0/root_files.rs
http/src/v0/root_files/add.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/subscription.rs
tests/connect_two.rs
tests/exchange_block.rs
tests/kademlia.rs
tests/multiple_listening_addresses.rs
tests/pubsub.rs
tests/wantlist_and_cancellation.rs

Some groundwork for peer and content discovery using `libp2p::kad`.
~~Very much a WIP with plenty of prototyping and wild `println!`s.~~
Cc https://github.com/rs-ipfs/rust-ipfs/issues/10

some groundwork for peer/content discovery

---

src/lib.rs
src/p2p/behaviour.rs
tests/kademlia.rs

An initial implementation of content discovery via DHT, where a `get_block` request that doesn't succeed locally results in a call to `Kademlia::get_providers`. It also fixes (AKA fixes in most cases) the previously prototyped display of Kademlia content keys, in this case `Cid`s.
cc https://github.com/rs-ipfs/rust-ipfs/issues/10

Initial content discovery

---

.github/workflows/ci.yml
Cargo.lock
http/Cargo.toml

Hoping to find something to help with #261:
- switch to using [lukka/run-vcpkg](https://github.com/lukka/run-vcpkg)
- get rid of the llvm dependency on windows (it was not needed)
- update openssl dep to 0.10.30

ci: use vcpkg for openssl on windows

---

unixfs/src/walk.rs

This is a first step towards #200

Remove unwrap usage in continue_walk

---

src/subscription.rs
tests/wantlist_and_cancellation.rs

Fixes the number of critical sections in SubscriptionFuture from 2 to 1, helping out with the hangs in exchange_block which have been recorded in #134. Also backports the `related_subs` cleanup from #264.

Adjust subscription locking

---

README.md
examples/client1.rs
examples/client2.rs
examples/fetch_and_cat.rs
examples/ipfs_bitswap_test.rs
examples/ipfs_ipns_test.rs
http/src/main.rs
http/src/v0.rs
http/src/v0/refs.rs
http/src/v0/root_files.rs
http/src/v0/root_files/add.rs
src/dag.rs
src/lib.rs
src/p2p/mod.rs
src/subscription.rs
src/unixfs/mod.rs
tests/connect_two.rs
tests/exchange_block.rs
tests/kademlia.rs
tests/multiple_listening_addresses.rs
tests/pubsub.rs
tests/wantlist_and_cancellation.rs

An attempt to have enhanced tracing capabilities, especially for test purposes; not everything is nicely assigned to a specific node, but it is definitely an improvement over what we have now.
This change allows us to see the following output in e.g. `exchange_block`:
```
running 1 test
Jul 30 16:13:42.567  INFO start{node="a"}: ipfs::p2p::behaviour: net: starting with peer id 12D3KooWKnZGUipX95ZGzqpQhPQ637euKNJ6b57H99mQcTt1hvox
Jul 30 16:13:42.577 DEBUG start{node="a"}: bitswap::behaviour: bitswap: new_handler
Jul 30 16:13:42.577 TRACE start{node="a"}: ipfs::p2p::swarm: new_handler
Jul 30 16:13:42.578 DEBUG bgtask{node="a"}: libp2p_tcp: Listening on "/ip4/127.0.0.1/tcp/35821"    
Jul 30 16:13:42.579  INFO start{node="b"}: ipfs::p2p::behaviour: net: starting with peer id …
```

improved tracing

---

http/src/v0/root_files.rs
unixfs/examples/get.rs
unixfs/src/walk.rs

Second take on #200 
`Entry` is now composed of `Bucket(...)` and `Metadata(MetadataEntry { ... })` to separate things that have and doesn't have metadata, which avoids returning optional values derived from a single entry-point.
Next PR will address the newly introduced double matching while iterating over `continue_walk` but it will require deeper logical changes.

Split Entry into two different enums to remove unnecessary expects

---

.github/workflows/ci.yml
conformance/setup.sh

node_modules: It's quite slow on windows (about 3min), linux (50s) and mac is in the between. This is a bit hacky given the patching and whatnot, but I think the hashFiles combination is good.
~/.cargo: this was never cached, but now it should be cached correctly `hashFiles(Cargo.lock)`.

ci: caching updates

---

bitswap/src/behaviour.rs
bitswap/src/protocol.rs
src/subscription.rs
tests/bitswap_stress_test.rs

We've been seeing `(empty message)` bitswap for a while, but these logs were bogus - this PR fixes those, and adds a small bitswap stress test that can be used for future bitswap debugging.
Also removes some noisy logging and, as a drive-by, fixes a subscription-related log.

fix bogus empty bitswap messages

---

Cargo.lock
Cargo.toml
src/lib.rs
src/repo/fs.rs

We no longer intend to pursue that feature; remove the related code.

Remove the rocksdb feature

---

tests/kademlia.rs

`#[ignore]` that Kademlia test that likes to randomly fail due to being dependent on actual network.

Ignore a flaky Kademlia test

---

Cargo.lock
Cargo.toml
http/Cargo.toml
http/src/lib.rs
http/src/v0/refs.rs
http/src/v0/root_files.rs
src/lib.rs

this uses the rust 1.45 features to remove recursion inside the macro. great for #284 which adds even more complicated async-stream(s).
good to go if CI passes.

fix: update async-stream to 0.3

---

Cargo.lock
Cargo.toml
examples/fetch_and_cat.rs
examples/ipfs_bitswap_test.rs
http/src/v0/block.rs
http/src/v0/refs/path.rs
http/src/v0/root_files.rs
src/ipns/dns.rs
src/repo/fs.rs
src/repo/mem.rs
src/subscription.rs
tests/bitswap_stress_test.rs
tests/exchange_block.rs
tests/wantlist_and_cancellation.rs

Some maintenance work so as not to conflict too much with the pending PRs:
- depend on cid instead of libipld where only Cid is used
- update the `domain` dep (big `Cargo.lock` wins)
cc #75

Some maintenance

---

src/lib.rs
src/p2p/behaviour.rs
src/p2p/swarm.rs
src/repo/mod.rs
src/subscription.rs

These changes were sparked by the following 2 observations:
- the logs sometimes indicate that a Kademlia query was executed twice
- `finish_subscription` didn't always result in futures being awoken
While the former remains a mystery (its occurrence is not correlated with subscriptions, meaning it's either some polling issue that eludes me or a bug in `libp2p`), investigating the `kad`<>`Subscription` route yielded a few improvements, namely:
- tweaked `kad` log levels
- proper `SubscriptionFuture` handling in `put_block`
- improved `SubscriptionRegistry` logs and a small fix
- simpler `SubscriptionFuture` type handling (it always returned a `Result`, so now it's a default)
- a `debug_assert` checking that we don't trigger zero-wake cases in `finish_subscription` during tests
- improved …

Some Kademlia debugging

---

bitswap/src/behaviour.rs
src/lib.rs
tests/bitswap_cleanup.rs

We currently don't properly clean up after a connection to a `Bitswap` peer is closed, which leads to leaking `Ledger`s; funnily enough, it seems that just uncommenting a pre-existing line solves the issue. In addition, add a relevant test.

Patch a Bitswap leak

---

Cargo.lock
http/Cargo.toml
http/src/v0/pubsub.rs

As `tokio` is the async executor in `http`.

Use tokio::test in http instead of its async_std counterpart

---

README.md
examples/client1.rs
examples/client2.rs
examples/fetch_and_cat.rs
examples/ipfs_bitswap_test.rs
examples/ipfs_ipns_test.rs
http/src/main.rs
http/src/v0.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/repo/mod.rs

Removes `SwarmTypes`, drops the generic from `IpfsOptions`, `RepoOptions` and `SwarmOptions` and simplifies the creation of `Ipfs`/`UnitializedIpfs` via more pattern-matching `move`s.
Rationale: since we already need to specify the type in order to create `IpfsOptions`, we might as well do that directly for `Ipfs` instead, without dragging the generic through all the options that don't even use it (they just carry `PhantomData`).

Ipfs object tweaks

---

src/lib.rs
src/subscription.rs
tests/wantlist_and_cancellation.rs

Turns out #174 was wrong, as the alternative required sprinkling block_on which made the whole thing worse. We shouldn't risk a deadlock with the mutex as we are not (can not) holding it across awaits.
Unwrap as we are not expecting subscriptions to panic and poison the mutex.

fix: go back to std::sync::Mutex

---

Cargo.toml
bitswap/Cargo.toml
http/Cargo.toml
unixfs/Cargo.toml

The usual convention for Rust crates that are a collaborative, open source effort is to put `<project> contributors` under the `[package] authors` in the `toml`.

Put "Rust-IPFS contributors" as package authors

---

src/lib.rs
src/p2p/behaviour.rs
src/p2p/swarm.rs
tests/connect_two.rs

While attempting to connect to a pre-connected `Multiaddr` didn't cause issues, duplicate `PeerId` attempts caused a hang.
I started by ensuring that the `PeerId` connection subscriptions are handled in the same manner as the `Multiaddr` ones. This, however, was insufficient. I then moved the creation of connection subscriptions before the connection event was pushed onto the swarm event stack, but it was not enough too. The final measure was to just ignore duplicate connection target attempts, which now doesn't even create a `Subscription`, but just causes the top-level call to return an error.

test duplicate connection attempts

---

src/subscription.rs

My suspects are either the enabled `tracing_subscriber` or the lock over `SubscriptionRegistry` taken in `get_subscriptions`; I've adjusted those and tightened the test's deadlines and wasn't able to trigger the issue while stress-testing. It might not suffice yet, but those changes won't hurt.

impl<T: Clone, E: Clone> Clone for Subscription<T, E>

---

src/subscription.rs

As far as I can tell this only happens to Kademlia queries and thus might be a `libp2p` bug; disable the sanity debug check for them to verify it.
Also, remove an outdated comment as a drive-by.

Work around the rare zero wakers CI failure

---

src/lib.rs
src/unixfs/mod.rs

This removes the previous API of:
* ipfs::Ipfs::add
* ipfs::ipfs::get
* ipfs::unixfs::File
Rationale for the removal is that ipfs-unixfs (under `unixfs/`, re-exported as `ipfs::unixfs::ll`) provides ability to do the similar use cases more or less. It does not however, provide means to have a nice api and persist stuff in an async way which is something we are lacking at the moment. I will probably file an issue for this API deficiency once I am through this.

Cleanup old unixfs api

---

Cargo.lock
Cargo.toml
http/Cargo.toml

Just a maintenance update to `Cargo.lock` via `cargo update` so that actual later dependency additions or deletions don't cause unrelated changes to it.

cargo update; remove unused rand feature

---

src/subscription.rs

`#[ignore]`d by default; it currently works pretty well for a reasonable amount of time.

Add a subscription stress test

---

_config.yml

This PR removes the _config.yml file, which is not needed since the website content lives in other repos.

Remove unneccesary Jekyll file

---

Cargo.lock
Cargo.toml
bitswap/Cargo.toml
unixfs/Cargo.toml

I decided to take a closer look on the features enabled in our dependencies and to the deps themselves and found a few more bits to tweak. Always nice to see some red in `Cargo.lock`.

More maintenance

---

unixfs/benches/ingest-tar.rs
unixfs/src/lib.rs
unixfs/src/symlink.rs

The minimal API and perhaps too verbose test cases around the feature. While I did check the cids to match some go-ipfs version cids, I think there might still be corner cases around even this very minimal API.

feat: unixfs symlink creation

---

Cargo.lock
unixfs/CHANGELOG.md
unixfs/Cargo.toml
unixfs/README.md
unixfs/src/file.rs
unixfs/src/file/adder.rs
unixfs/src/lib.rs
unixfs/src/symlink.rs

Per semver the next must be a minor bump at least. While I don't have a concrete path forward to 1.0 in mind for this crate I am sure we'll be doing smaller bits and bobs soon as we approach a rust-ipfs release as well.

Prepare unixfs release v0.1.0

---

Cargo.lock
http/Cargo.toml
http/src/v0/id.rs
http/src/v0/swarm.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/p2p/swarm.rs
src/subscription.rs
tests/connect_two.rs

not verified but indirectly used by the conformance tests when dialing a peer with an expected peerid.
Not 100% sure if this should be done, at least long as #105 is done at least to accept the multiaddrs with `/p2p/`.

add: p2p suffixes to multiaddrs from identify

---

conformance/package-lock.json
conformance/package.json
conformance/patches/add.patch
conformance/patches/local_refs.patch
conformance/test/index.js
http/src/v0/version.rs

`package.json` updates:
```
"interface-ipfs-core": "0.137.0" > "0.139.0"
"ipfs-http-client":    "^44.3.0" > "46.0.0"
"ipfs":                "^0.43.0" > "0.49.0"
```
The new version of the conformance test suite requires 2 new `/version` fields (blank for now) and a patch for one of the `add` tests (as we don't expose `/files` yet). ~~It also allows us to transition the `Repo` to only keep `Multihash`es instead of `Cid`s, as `refs_local` is expected to return `Cid v1` with `Codec::Raw`, which can be produced on the fly.~~ (deferred)

Conformance test suite updates

---

http/src/v0/swarm.rs
src/lib.rs
src/p2p/addr.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/p2p/swarm.rs
src/subscription.rs
tests/connect_two.rs

Whether a `Multiaddr` contains `Protocol::P2p` (i.e. essentially `/p2p/PeerId`) or not has a lot of bearing on conformance tests, the internal object and APIs and error-handling. Since it is easy to introduce related human errors, it would be a good idea to enforce some type safety here by introducing 2 wrapper objects: `MultiaddrWoPeerId` and `MultiaddrWithPeerId`.
The extent to which they should be applied (in lieu of `Multiaddr`) is a matter for discussion - in my initial attempt I decided to apply them quite liberally, as it results in more type safety (there are still a few plain `Multiaddr`s left though).

Use explicit Multiaddr wrappers

---

Cargo.lock
Cargo.toml
bitswap/Cargo.toml
src/p2p/behaviour.rs

`libp2p 0.24` enables us to only depend on a single async executor (in our case, `tokio`).
A small change in the code, a big win for `Cargo.lock`.

Update libp2p and use TokioMdns

---

src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/repo/mod.rs
src/subscription.rs
tests/kademlia.rs

I've been planning to add some of the `/dht` functionalities and since it looks like it's going to be a bit complicated, I'd like to split these upcoming changes into meaningful bits.
First up: the ability to get results from `Kademlia`'s `SubscriptionRegistry`. While working on this I noticed that some of the results can be provided multiple times (e.g. `BootstrapOk` that indicates the number of peers left to bootstrap against), which should solve the mystery of `Kademlia` not adhering to the `debug_assert` we have in `SubscriptionRegistry::finish_subscription`.
As an accidental drive-by there's also a fix to the `Kademlia` bootstrap test which was silently failing after we introduced the `Multiaddr` wrappers.

Introduce KadResult

---

http/src/v0/dag.rs
http/src/v0/refs.rs
http/src/v0/refs/path.rs
http/src/v0/root_files.rs
src/dag.rs
src/path.rs

First step towards solving the #238 
- fix `ipfs::IpfsPath`
- swapped `ipfs::path::SubPath` for `String` (commit has reason)
- removed `IpfsPath::push(&mut self, segment: impl Into<SubPath>)`
- remove the implicit ending empty path segment (seemed intentional, don't know why that was there)
- migrate tests
- most notably add support for `cid/a/b/c` cases
- move "good_but_unsupported" over to "good_paths" (as ipfs::IpfsPath validates more)
- make ipfs-http use `ipfs::IpfsPath`
This specifically doesn't include:
- separation of different kinds of IpfsPaths (`CidPath`, `IpnsPath`)
- instead there is currently an expect over at http side for cid paths
- probably a good idea to refactor out the `Vec<String>` (sub)path somehow; it might be heavily reusable for unixfs for example
- moving the …

fix: make ipfs-http to use ipfs::IpfsPath

---

http/src/v0.rs
http/src/v0/dht.rs
src/lib.rs
src/p2p/addr.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/repo/mod.rs
src/subscription.rs
tests/kademlia.rs

Builds on https://github.com/rs-ipfs/rust-ipfs/pull/319, only the last 2 commits are new.
Introduces `Ipfs::find_peer` and `/dht/findpeer` that return addresses belonging to the given `PeerId`; if they are connected to already, the values are returned right away, otherwise the local DHT records are checked.
Blocked by https://github.com/rs-ipfs/rust-ipfs/pull/319.

Implement Ipfs::find_peer and /dht/findpeer

---

.github/pull_request_template.md

This PR removes the "top-level command" requirement from the PR template. We don't have a CLI yet and we can add it back in when we do.

Remove top-level command item from PR template

---

src/unixfs/cat.rs
unixfs/src/dagpb.rs
unixfs/src/dir.rs
unixfs/src/dir/builder.rs
unixfs/src/dir/builder/buffered.rs
unixfs/src/dir/builder/dir_builder.rs
unixfs/src/dir/builder/iter.rs
unixfs/src/dir/directory.rs
unixfs/src/dir/sharded_lookup.rs
unixfs/src/file.rs
unixfs/src/file/adder.rs
unixfs/src/file/reader.rs
unixfs/src/file/visit.rs
unixfs/src/lib.rs
unixfs/src/pb.rs
unixfs/src/pb/merkledag.rs
unixfs/src/pb/unixfs.rs
unixfs/src/symlink.rs
unixfs/src/test_support.rs
unixfs/src/walk.rs

First step towards no_std compatibility for unixfs

Use alloc and core crates where they are applicable

---

src/repo/mod.rs

This one was funny to debug: when calling `add` in our [ipfs-enabled substrate fork](https://github.com/rs-ipfs/substrate/tree/offchain_ipfs_bleeding_edge), I was sometimes getting a `oneshot canceled` eror, even though there was no usual `Ipfs` vs. `IpfsFuture` communication to issue the top-level call; a little bit of investigation suggests that this is caused by the fact the `offchain::ipfs` calls are restricted by a deadline and thus the temporary sender (for `RepoEvent::ProvideBlock`) can die during execution. Since we are pretty lax (and rightfully so, as it's not a crucial functionality) in terms of that event reaching its destination, we should do the same about receiving the related answer.

fix: make the ProvideBlock rx behavior match the sender in put_block

---

Cargo.lock
http/Cargo.toml
http/src/v0/refs.rs
src/lib.rs
src/refs.rs

This PR moves `refs` from `ipfs-http` to `ipfs`. Ended up moving only a `iplds_refs` which needs pre-resolved `IpfsPaths`. As for short term I think this should help towards #11.
I was originally planning to make this into a version which would accept both `IpfsPath` (or `CidPath`) and already projected `(Cid, Ipld)` but the duplication of code would be quite unavoidable, as the http side will have to "buffer" all IpfsPath resolution *before* calling a version of `iplds_refs` which would accept a `TryStream<Ok = (Cid, Ipld), Error = _>` instead of `IntoIterator<Item = (Cid, Ipld)>`. I did continue this solution and did try out prefetching options for unixfs_cat for example, but I'll leave them for next PRs since they will complicate the API quite a bit.
While moving the tests, I removed …

refactor: move refs as Ipfs::refs and ipfs::refs::iplds_refs

---

examples/fetch_and_cat.rs

Minor changes to fetch_and_cat I found useful while testing the prefetching (and so the streaming ipfspath refs).

example: fetch_and_cat tuneup

---

conformance/test/index.js
http/src/v0/dht.rs

A small fix that allows us to pass one more `dht` conformance test, namely `"should return the other node in the query"`.

pass another dht.query conformance test

---

Cargo.toml
src/lib.rs
tests/kademlia.rs

Builds on https://github.com/rs-ipfs/rust-ipfs/pull/344, only the last 5 commits are new.
Adds a `test_dht_with_go` feature which allows to run the DHT tests with a go-ipfs node in the middle of the chain of rust-ipfs nodes, as long as the `GO_IPFS_PATH` environment variable pointing to the go-ipfs binary is provided.
~~As of now, the DHT tests using a go-ipfs node need to be run one at a time; an appropriate FIXME is included.~~
Also changes the test `Node` object to advertise the `/ipfs/lan/kad/1.0.0` kad protocol that is also used by go-ipfs in tests.
Blocked by https://github.com/rs-ipfs/rust-ipfs/pull/344.

Test go-ipfs DHT interop

---

Cargo.toml
conformance/test/index.js
http/src/v0/pin.rs
http/src/v0/pin/add.rs
http/src/v0/support/option_parsing.rs
http/src/v0/support/serdesupport.rs
src/lib.rs
src/refs.rs
src/repo/mem.rs
src/repo/mod.rs

This PR adds the remaining `pin/*` APIs, with a bad implementation of recursive pinning. Aim is to inch forward to see a more proper implementation.
Compared to older pin storage implementations in go-ipfs at least this jumps right into using a "datastore" similar to the previous implementation. However I quickly found that the pin storage could not work on the simple datastore API. Instead of turning the datastore API into versioned and Repo level pin operations retryable on races this adds a version of `PinStore` which assumes locked access.
Recursive pinning is the slowest and most space inefficient variant: store all indirect pins. It doesn't seem wise but I am inclided to keep that at least for this PR. When adding a recursive pin, first the root is marked as `Recursive::Intent`, …

Continued pinning

---

Cargo.toml
http/src/main.rs
src/lib.rs
src/repo/fs.rs

This fixes the racing writers issue which the implementation has had for a long time; multiple writers would come in and all would write over the same file, multiple times, allowing readers to observe partial writes in the meantime. This covers most of the changes.
In addition ipfs-http now uses the file block store. There was some transient macosx failures.

fix: fs blockstore

---

Cargo.lock
Cargo.toml
src/lib.rs
src/p2p/mod.rs
src/p2p/swarm.rs
src/p2p/transport.rs

Not quite sure how to best test this without having a test that uses the dns of the CI server. Any ideas?

This PR uses libp2p dns, so that /dns4 and /dns6 multiaddrs can be dialed.

---

src/lib.rs
src/p2p/behaviour.rs
tests/kademlia.rs

While I'm looking at the curious Windows crashes with `/dns` and `/resolve`, we can expand territories elsewhere: I've had these functionalities implemented in a branch building one the recently merged PRs; there's no counterpart HTTP endpoints yet, as the conformance tests use functionalities that we're not implementing yet; these features are less interesting for the HTTP API anyway.

add DHT get and put

---

.github/workflows/ci.yml
Cargo.toml
tests/common/interop.rs
tests/common/interop_go.rs
tests/common/mod.rs
tests/connect_two.rs
tests/kademlia.rs

Initially this PR only added `go-ipfs` interop DHT tests to the Linux CI run. Even if that functionality was a tiny amount of code, I might have gotten lost in the moment and gone a bit too far with extending this PR to also introduce a `jsipfs` interop functionality :sweat_smile: - I can split it out if that's desirable.
In any case, the individual commits describe specific changes; the diff seems big, but it's mostly moving stuff around, as almost all of the `go-ipfs` interop code is compatible with `jsipfs`. The `jsipfs` interop tests are not run in the CI yet.

add go-ipfs DHT interop tests to the CI, enable jsipfs interop tests

---

Cargo.lock
Cargo.toml
conformance/test/index.js
examples/ipfs_ipns_test.rs
http/src/v0.rs
http/src/v0/ipns.rs
src/dag.rs
src/ipns/dns.rs
src/lib.rs
src/path.rs

Add a rudimentary implementation of the `/dns` and `/resolve` endpoints; putting it out there already, as due to the similarity of these two endpoints I'm not 100% sure how much we want to "condense" their inner workings.
This upgrades or conformance suite stats from
```
170 passing
50 pending
```
to
```
178 passing
42 pending
```

Implement /dns and /resolve

---

unixfs/src/file/adder.rs

Default is already included in the standard std prelude

Remove Default full path

---

http/src/main.rs
src/lib.rs

This PR allows us to specify the desired listening address(es) of the node. For now, these addresses are just additions to the current randomly assigned listening address, as I'm not sure what to pick as the default; once we know this, the only change needed (besides the default listening addresses being put in the config) is to remove the following line from `p2p::create_swarm`:
```
// Listen on all interfaces and whatever port the OS assigns
Swarm::listen_on(&mut swarm, "/ip4/127.0.0.1/tcp/0".parse().unwrap()).unwrap();
```
Another question is how to handle a situation where one/all of the supplied addresses can't be listened on:
- refuse to start?
- assign a random different address?
- only log errors if at least one works?
This is currently unresolved, but since the PR preserves the …

Configurable listening addrs

---

src/dag.rs
src/lib.rs
src/refs.rs
tests/bitswap_cleanup.rs
tests/bitswap_stress_test.rs
tests/common/interop.rs
tests/common/mod.rs
tests/exchange_block.rs
tests/pubsub.rs

This PR improves our multi-node testing capabilities by:
- introducing a `spawn_connected_nodes` function and the related `Topology` object, allowing us to automate the creation of various test scenarios
- adds the `PeerId` and listening addresses to the `Node` object used in tests, to remove the need for calling `.identity()` every time a node is created
These new functionalities are not used everywhere yet and can probably be improved further, but it's a good starting point.

Improve multi-node tests

---

src/repo/mod.rs

I've found this issue while doing runs of the usually `#[ignore]`d tests, namely with the `bitswap_stress_test`. In `debug` builds it would trigger a `debug_assert` that verifies that we don't finish non-existent subscriptions (which in itself is not a big deal, but it is undesirable).
The reason was that a call to `get_block` that doesn't find the `Block` in the local repo creates a subscription for that `Block` (but _not_ if it was found), while `put_block` always finished a subscription for the `Block`, even if it had already existed in the repo. The solution was to just move `finish_subscription` under the `if let BlockPut::NewBlock = res` block, meaning that it's triggered only if the block that was put was new to the repo.

Finish Block subscriptions only if a subscription had been created

---

tests/common/interop.rs

This should at least take care of the `dead_code` warnings; the error reported at `repo::fs::blocks::232` keeps eluding me (not even visible in the detailed logs).

remove the dead_code warnings in CI runs

---

tests/common/interop.rs
tests/pubsub.rs

Builds on https://github.com/rs-ipfs/rust-ipfs/pull/368, only the `test: ...` commits are new.
Extends the interop test functionalities so that arbitrary HTTP API calls can be made for the foreign nodes; I attempted to use them in order to introduce a `pubsub` interop test, but it doesn't work yet. Since the underlying issue might cause the PR to grow, I'd prefer to merge it as-is, with the new `pubsub` interop test currently `#[ignore]`d.
Blocked by https://github.com/rs-ipfs/rust-ipfs/pull/368.

Improved interop test functionalities, prepare a simple pubsub interop test

---

conformance/patches/bootstrap.patch
conformance/test/index.js
http/src/v0/bootstrap.rs
src/lib.rs
src/p2p/behaviour.rs

~~Builds on https://github.com/rs-ipfs/rust-ipfs/pull/371, only the last 6 commits are new.~~
Fixes the remaining 5 `bootstrap` conformance tests, bringing our overall score past 200 passing :muscle::
```
201 passing (52s)
48 pending
```
As usual, the commits describe specific changes; most are pretty self-explanatory, with the exception of the new patch:
```
-      expect(peers).to.have.property('length').that.is.gt(1)
+      expect(peers).to.have.property('length').that.is.eq(0)
```
The reason behind that one is that our HTTP test node only carries `Identity` config information - there is no `Bootstrap` key available in the config file, so the number of default bootstrapper addresses is `0`.
~~Blocked by https://github.com/rs-ipfs/rust-ipfs/pull/371.~~

Full /bootstrap support

---

src/p2p/addr.rs
src/p2p/behaviour.rs

This is an `#[ignore]`d test due to it using the global network, but it's a practical debugging tool regardless; this time it helped fix 2 issues:
- the handling of `Multiaddr`s ending with `/p2p-circuit`
- searching for `Block` providers using the full `Cid` instead of just the `Multiaddr` (we've noticed this before, but it got lost in the TODOs :stuck_out_tongue:)

Fix 2 issues triggered with the dht_popular_content_discovery test

---

conformance/test/index.js

This PR un-skips one conformance test that works now that we have pinning. This brings our number up by one! :firecracker:

Enabling pinned blocks test

---

src/repo/fs/blocks.rs

Fixes #386 -- at least there are no more unhandled panics, seems that the blockstore is still racy but I am not sure how to fix it right now. I am not 100% what caused those panics but I suspect it was related to having multiple broadcast::Sender's alive in the blocking task queue trying to send to receivers which were already dropped because the outer async context was dropped.
In addition there are even more comments, minor comment adjustments, minor splitting to comment less but more clear code.
First commit is the fix.

fix: unhandled panics in the fs blockstore

---

conformance/patches/bootstrap.patch
src/config.rs
src/p2p/behaviour.rs

Alters the `BOOTSTRAP_NODES` list to contain only the currently working addresses and changes the behavior of `Swarm::remove_bootstrappers` to not use the config file, but rather the aforementioned in-memory list.
Cc https://github.com/rs-ipfs/rust-ipfs/issues/356

fix: restore bootstrappers from static list, update the bootstrapper list

---

http/src/config.rs
http/src/main.rs
src/lib.rs
src/p2p/mod.rs

Remove the default random listening address, listen to no addresses by default.
Cc https://github.com/rs-ipfs/rust-ipfs/issues/356

remove the default random listening address

---

.github/workflows/ci.yml
Cargo.toml
README.md
examples/dag_creation.rs
src/lib.rs

Moving the code example from the README to the `examples` simplifies our CI setup and makes one of the runs redundant.

Move the README example, remove the nightly feature and CI run

---

bitswap/src/behaviour.rs
bitswap/src/block.rs
http/README.md
http/src/config.rs
http/src/lib.rs
http/src/v0.rs
src/dag.rs
src/error.rs
src/ipld/ipld_macro.rs
src/ipld/mod.rs
src/ipns/mod.rs
src/lib.rs
src/p2p/pubsub.rs
src/path.rs
src/refs.rs
src/repo/fs.rs
src/repo/fs/blocks.rs
src/repo/mod.rs
src/unixfs/mod.rs

Adds at least top level documentation for many types, hides some unnecessary re-exports, removes warnings from nightly rustdoc on bad links, and so on.
Cc: #197 (this leaves us with 185 errors)

Refresh docs

---

examples/dag_creation.rs
examples/fetch_and_cat.rs
http/src/main.rs
http/src/v0.rs
http/src/v0/root_files/add.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs

Supercedes #345.
Rebased and fixed on top of #392 master.

Simplified node internals and creation v3

---

Cargo.lock
unixfs/CHANGELOG.md
unixfs/Cargo.toml

Updates the changelog and bumps the version to 0.2.0. I'll tag and release after merging.

ipfs-unixfs: update changelog, bump version

---

bitswap/Cargo.toml

whoops.
This PR adds the necessary metadata bitswap/Cargo.toml, so that I can publish it.

chore: add missing Cargo.toml metadata

---

Cargo.lock
Cargo.toml

This PR updates Cargo.toml, so that I can release it.
I hope adding the `version` for the `path` deps does the trick, at least `cargo publish --dry-run` seems to produce an ok crate, with:
```
[dependencies.ipfs-bitswap]
version = "0.1"
[dependencies.ipfs-unixfs]
version = "0.2"
```
The crate ends up containing the Cargo.lock file which I am not so sure if it should be excluded?

Prepare ipfs release

---

CONTRIBUTING.md

This PR fixes a typo in `CONTRIBUTING.md`.

Doc: fix CONTRIBUTING.md typo

---

.github/pull_request_template.md
CHANGELOG.md
CONTRIBUTING.md
unixfs/CHANGELOG.md

Closes #171:
- CONTRIBUTING.md description, algorithm for choosing the CHANGELOG file
- pull_request_template.md
- CHANGELOG.md and unixfs/CHANGELOG.md preparation with `# Next`

Start tracking changelog

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR adjusts issue templates to remove screenshots, replaces steps to reproduce guide related to GUI apps with (code) and removes the redundant label prefix from issues.

Tune issue templates

---

Cargo.lock

patch level updates, biggest is probably new version of futures.
I don't think this should go to changelog either.

chore: upgrade deps

---

CHANGELOG.md
examples/fetch_and_cat.rs
http/src/v0/bootstrap.rs
src/config.rs
src/lib.rs
src/p2p/behaviour.rs
tests/kademlia.rs

Fixes #405 and also:
- makes sure ipfs.restore_bootstrappers is used in the `dht_popular_content_discovery` test
- adds a test case making sure we can parse all config::BOOTSTRAP_NODES
- ~adds some FIXMEs we couldn't decide yet on the other /bootstrap impl~ handled
- expose ipfs::config to allow http to access ipfs::config::BOOTSTRAP_NODES to enable the http api semantics
- keep exposing the delta semantics in ipfs.restore_bootstrappers
- use ipfs.restore_bootstrappers in examples/fetch_and_cat.rs via new `--default-bootstrappers` option/mode
- add tracing to *_bootstrapper methods

fix restore_bootstrappers doesn't enable content discovery

---

CHANGELOG.md
Cargo.lock
Cargo.toml
examples/fetch_and_cat.rs
src/lib.rs

Tracked in #413. This turned out a bit misc PR with the comment removal from fetch_and_cat and all that.

Prepare 0.2.1 release

---

.github/workflows/ci.yml
src/repo/mod.rs

In this PR:
- Fixes #407 
- "no artifacts found" nagging for missing core files
- 1.47 clippy warning
Github had [a security issue and will be deprecating some functionality](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/). I learned this from the easy-to-miss workflow warnings.

Fix gha deprecations

---

http/src/main.rs

This PR changes the default `IPFS_PATH` from `.ipfs` to `.rust-ipfs` as mentioned in #402. 
I _think_ this is all that's needed?

fix(http): change default ipfs path to .rust-ipfs

---

CHANGELOG.md
http/src/config.rs
http/src/main.rs

This PR introduces a `Profile` abstraction to allow the customisation of port selection as discussed in #402.
Two profiles are supported: 
- `Test` for use with conformance tests (ephemeral port selection)
- `Default` serves on `4004`

feat(http): create Profile abstraction to allow port choice

---

http/README.md

This is a first draft of the tutorial mentioned in #402. 
It currently covers:
- installing rust
- configuration of the `IPFS_PATH` 
- `-- init`
- `-- daemon`
- `ipfs id` from the go-ipfs CLI

docs(http): initial draft of tutorial

---

.github/workflows/ci.yml
CHANGELOG.md
tests/common/interop.rs

We were using `0.6.0`, this upgrades to `0.7.0`. 
I also removed the `--bits` option as `0.7` uses `ed25519` by default.

Update to go-ipfs 0.7.0 (used in interop tests) 

---

CHANGELOG.md
Cargo.lock
Cargo.toml
http/src/main.rs
src/lib.rs
src/repo/fs.rs
src/repo/mem.rs
src/repo/mod.rs

supersedes #426 and resolves #243. 
This implements repo locking with fs2. The only concern for this crate is that it is poorly maintained but the functionality we need seems stable enough for now. 
Certain tests are currently failing, notably because multiple nodes are being created with the same repo (dag tests for instance). Not sure what the solution to this will be...
Update: running tests with `--test-threads=1` passes all unit tests. The integration tests fail (I think because multiple nodes are being spun up with the same repo). 
Update 2: all green, making sure test nodes use a different temp dir for the repo fixed the tests.

feat: repo locking with fs2

---

src/dag.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/pubsub.rs
src/repo/mem.rs
src/repo/mod.rs

Follow up to #409 and part of #197.

Fix more missing doc warnings

---

.github/workflows/ci.yml
bitswap/src/ledger.rs
http/src/config.rs
src/ipld/dag_json.rs
src/path.rs
tests/common/interop.rs
unixfs/CHANGELOG.md
unixfs/src/walk.rs

Address latest warnings with 1.48. It feels like we should have gotten the `some_str == ""` in earlier versions as well, other than this these are just minor idiomatic changes. Also includes:
- a previously forgotten panic documentation on ipfs-unxifs walker
- workflow fix to enable merges again (see #436)
Closes #436.

Clippy changes for 1.49, doc fixes

---

Cargo.lock
Cargo.toml
src/lib.rs
src/repo/kv.rs
src/repo/mod.rs

This PR is for using key-value db like sled as DataStore and PinSotre, so that it is more efficient for pinning and easy to realize MFS.
The FsDatastore is inefficiency now, when checking a indirect pinned cid, all file in the FsDatastore will be visited and read, what more important is that it is hard to distinguish the data for pinning and the data for DataStore. The key-value db like sled will bring convenience and efficiency in the next work with its high efficiency and easy key/value operation. Leveldb may be the first choice of key-value dbs, but now there are no suitable rust leveldb crates; Sled is fast and simple, and it is usable on servers and phones from any C-compatible language.
This PR is the reopen of [PR434](https://github.com/rs-ipfs/rust-ipfs/pull/434). For there is …

Use Key-value DB for DataStore and PinStore

---

.github/bors.toml

This PR will allow `bors r+` before there are any review approvals. It will be good for smaller PRs like #436 or things which happen right before releasing. Alternatives include:
- to request and await for approvals (current situation)
- to merge without bors -- this is something I'd like to avoid doing
Now bors uses the PRs configuration so I don't require any approvals on this, but it has to come after #436 so that the workflow is fixed so at least this is gated on that :) So @aphelionz, @ljedrz, or anyone interested in this, how do you see this? I think the policy should still be to review all non-boring maintenance PRs.
I did check CONTRIBUTING.md and found that there is nothing regarding this.
I'll merge this at the earliest of tomorrow morning on +02:00.

ci: no longer require review approvals to merge

---

.github/workflows/ci.yml

The DHT interop tests were accidentially ran also with the `matrix.platform.cross` targets, this stops it.

ci: stop running dht interop tests for cross targets

---

CHANGELOG.md
src/repo/common_tests.rs
src/repo/fs/pinstore.rs
src/repo/kv.rs
src/repo/mem.rs
src/repo/mod.rs

This enables the pinstore to use transactions for almost all operations. Big ticket TODOs remaining:
- handling duplicate indirect pins (missing test)
- handling pin combinations (missing test)
- cidv0 compatible cidv1 normalization (missing test)
- the str representation could probably be changed?
- sled usage still needs to be wrapped in spawn_blocking
In smaller changes:
- makes PinMode Copy
- extracts a `PinModeRequirement` out of the `Option<PinMode>` which is hopefully more readable (list, query)
CC: @fetchadd, got the PR I promised made. Do you have any ideas? Sadly the changeset is probably quite difficult to review. I could split it up to have just the small fixes followed by the transactional stuff, but the smaller changes can probably by diffing only up until some commits.

Transactional sled pinstore

---

.github/workflows/ci.yml

This PR delays the changing to `cargo ndk` version 2.0, which has different cmdline API.

ci: hold back at cargo ndk 1

---

CHANGELOG.md
src/lib.rs
src/p2p/mod.rs
src/repo/fs/pinstore.rs

This PR changes how the spans are set up from IpfsOptions and in UninitializedIpfs. While debugging the now ignored test (see #450) I found that the spans were configured wrong and thus none of the multiple nodes created by `spawn_nodes` could be differentiated.
This also renames the spans to more logical from the "$root" given at `IpfsOptions::span`:
`Span::current` => `$root:init`
`Span::current` => `$root:init:swarm`
`$root:swarm` => `$root:exec` (literally the executor libp2p spawns futures through)
`$root` => `$root:bg_task` => `$root:swarm` (background task)
`$root` => `$root:facade` (futures created through Ipfs::* methods)
Still very far from perfect, but perhaps a step into better direction.

Fix multinode test spans

---

CHANGELOG.md
src/lib.rs
src/p2p/addr.rs
src/p2p/swarm.rs
src/subscription.rs
tests/connectivity.rs

The correct way to connect to a peer is in my understanding to DialPeer and then proceed to give the address of that said peer from `NetworkBehaviour::addresses_of_peer`. While doing this, the previous workaround for missing events from banning a peer (the way we force a disconnect) was also necessary to fix.

Fix connecting to peers

---

src/p2p/swarm.rs
src/subscription.rs

This PR fixes the swarm tests and yet another swarmapi related panic reachable through only the swarmapi "unit tests". It also adds a two new cases which would had been quite ugly add to under `tests/`. 
First of all, the test had been broken long time ago in a rust-libp2p update when the listening address adding became asynchronous.
The additional panic exposed by now working test case comes from the `inject_connected` never arriving when only using SwarmApi as the only behaviour. It uses the DummyProtocolHandler which opens no streams and demands keepalive, the connection is immediatedly closed.
The additional test cases cover connecting to wrong peerid, and dialing multiple addresses when only first one succeeds, the second errors.

Fix swarmapi tests and add more cases

---

Cargo.lock
Cargo.toml
src/ipns/dnslink.rs

Ahead next version of libp2p-dns which will finally use trust-dns. Added FIXMEs and more importantly get rid of the windows specific ipconfig, custom future impl around selectok. This shouldn't really affect anything so I doubt this needs to be mentioned in changelog. The IPNS story is quite weak as it is.

Migrate dnslink to trust-dns

---

http/src/v0/root_files.rs

Get rid of work with filesystem in fs-unrelated tests.
No more problems like https://github.com/rs-ipfs/rust-ipfs/issues/465 lead to tests failure.

In-memory reading from tar archives instead of extract to temp folder

---

CHANGELOG.md
Cargo.toml
benches/hashed-map-cid.rs
bitswap/Cargo.toml
bitswap/src/behaviour.rs
bitswap/src/ledger.rs
src/repo/common_tests.rs
src/repo/fs/blocks.rs
src/repo/fs/pinstore.rs
src/repo/mem.rs
unixfs/Cargo.toml
unixfs/src/test_support.rs

This PR implements a fix for #258, ie. using hash_hasher to improve performance in HashMaps/Sets what utilize Cid as key. hash_hasher provides approx. 40% increase in performance in this case.
There are two things that still need to be done:
- code is **not linted** yet, since this will be done in a separate PR by Mirko,
- a simple benchmark is included for the sake of comparing HashedMap<Cid,> vs HashMap<Cid,>; Imho this bench should not be merged.

Use hash_hasher in hashmaps/sets where the key is a Cid/Multihash #258

---

.github/workflows/ci.yml

This PR improves the CI caching, roughly halving the time required when caches are hit (no dependency or toolchain changes).
Overview of changes:
- Use [rust-cache action](https://github.com/Swatinem/rust-cache). This forms the bulk of the time improvement as Rust dependencies are now cached.
- Improve npm caching for conformance tests. This trims 2-3 minutes of build time.
- Improve job and step naming.
- Add a manual trigger for the workflow.
- Remove core dump for macos, no longer required.
Further details can be found in the commits.
I've been running into sporadic conformance test failures on windows ([link to run](https://github.com/Mirko-von-Leipzig/rust-ipfs/actions/runs/1135372291)):
```
1) .pubsub.subscribe
multiple connected nodes
should send/receive 100 messages:
FetchError: …
```

ci: cache improvements

---

CHANGELOG.md
Cargo.toml
bitswap/Cargo.toml
bitswap/src/error.rs
bitswap/src/protocol.rs
http/Cargo.toml
src/lib.rs
src/p2p/addr.rs
src/p2p/behaviour.rs
src/p2p/pubsub.rs
src/p2p/swarm.rs
src/p2p/transport.rs
unixfs/Cargo.toml

This PR is a follow up of #463.
It includes the following:
- upgrading libp2p to [v.0.39.1](https://github.com/libp2p/rust-libp2p/releases/tag/v0.39.1)
- upgrading some other deps (e.g.: prost, prost-base, quick-protobuf, base64), **excluding cid and multihash**
- fixes to tests that started failing following upgrade to libp2p v.0.38 in #463
Incoming shortly:

chore: upgrade to libp2p 0.39

---

CHANGELOG.md
src/p2p/addr.rs
src/p2p/swarm.rs
unixfs/src/dir/builder/iter.rs

This is a follow up of https://github.com/rs-ipfs/rust-ipfs/pull/472. There are two changes introduced:
* remove eq_greedy as `Multiaddr` in `SwarmApi::pending_{addresses, connections}` contains p2p, align conversions accordingly (https://github.com/rs-ipfs/rust-ipfs/commit/136496f7de57d72782cf4c06108733321b05e9fc),
* explicitly use `MultiaddrWithPeerId` in `SwarmApi::pending_{addresses, connections}` (https://github.com/rs-ipfs/rust-ipfs/commit/3b6f69530f633a9db4545fffe4b054dc69a760fc).
The former (https://github.com/rs-ipfs/rust-ipfs/commit/136496f7de57d72782cf4c06108733321b05e9fc) works fine without the latter (https://github.com/rs-ipfs/rust-ipfs/commit/3b6f69530f633a9db4545fffe4b054dc69a760fc), however I am leaning more towards keeping both changes. Encoding the information about …

Swarm cleanup following libp2p upgrade to v0.39.1

---

Cargo.toml

When including rust-ipfs as a dependency in any crate, it fails with the following error:
```
error: failed to select a version for the requirement `aesni = "^0.7"`
candidate versions found which didn't match: 0.99.99, 0.10.0, 0.9.0, ...
location searched: crates.io index
required by package `aes v0.4.0`
... which is depended on by `aes-gcm v0.6.0`
... which is depended on by `snow v0.7.1`
... which is depended on by `libp2p-noise v0.30.0 (/home/alexander/dev/misc/rust-libp2p/transports/noise)`
... which is depended on by `libp2p v0.37.1 (/home/alexander/dev/misc/rust-libp2p)`
... which is depended on by `libp2p-relay v0.2.0 (/home/alexander/dev/misc/rust-libp2p/protocols/relay)`
```
This fix updates the libp2p version into one that has a fix for this dependency and now it compiles fine

Fixing build issue described in: https://github.com/libp2p/rust-libp2p/issues/2231

---

.github/workflows/ci.yml
conformance/package-lock.json
conformance/package.json
http/src/v0/dht.rs
http/src/v0/id.rs
http/src/v0/ipns.rs
http/src/v0/pin.rs
http/src/v0/root_files.rs
http/src/v0/swarm.rs
http/src/v0/version.rs
src/ipld/dag_json.rs
src/ipns/dnslink.rs
src/ipns/mod.rs
src/repo/fs.rs
unixfs/CHANGELOG.md
unixfs/src/dir/builder/custom_pb.rs
unixfs/src/lib.rs

I had forgotten some old urls there which are sure to cause build failures, as seen in the #479.

build: fix wrong repo urls, clippies

---

CHANGELOG.md
src/dag.rs
src/ipld/dag_cbor.rs

This change proposes a fix for #492 . `Ipld::Map` keys are sorted according to [the strictness guidelines in the DAG-CBOR spec](https://github.com/ipld/ipld/blob/master/specs/codecs/dag-cbor/spec.md#:~:text=The%20keys%20in,order%20sorts%20earlier.) when encoding them as DAG-CBOR.

Strict ordering for DAG-CBOR-encoded map keys

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.toml
bitswap/Cargo.toml
bitswap/src/behaviour.rs
conformance/setup.sh
conformance/test/index.js
http/Cargo.toml
http/src/config.rs
http/src/v0/id.rs
src/lib.rs
src/p2p/behaviour.rs
src/p2p/mod.rs
src/p2p/pubsub.rs
src/p2p/swarm.rs
tests/pubsub.rs

This PR updates the dependency on libp2p. This is needed because currently building `ipfs-http` fails with an ambiguous type error inside of `libp2p`.

Update libp2p to v0.43.0

---

CHANGELOG.md
http/src/config.rs
http/src/main.rs

This PR adds default values for the `ipfs init` command to be more like the go-ipfs `ipfs init`. `--bits 2048` and `--profile default` are the default flags if they not overridden.
I've also included an profiles length check that is more accurate and injects the default profile if none was provided. Plus a small update to an error print statement because 1024 bits for a RSA key is too low.

feat(http): add default values for --bits and --profile in ipfs init

---

CHANGELOG.md
src/p2p/swarm.rs

Return time since connection if no round trip yet

---

fuzz/.gitignore
fuzz/Cargo.toml
fuzz/fuzz_targets/decode_ipld.rs

This PR adds a fuzz harness for IPLD decoding, so that the decoder can be more resilient from panics, etc.
- wanted? 
- not necessary as it isn't user facing?

IPLD fuzzing

---

src/ipld/dag_cbor.rs

This PR fixes two crashes that the #510 fuzzer found.
I am not sure if 64k is a reasonable limitation for `bytes` and `list` items, but please let me know what they should be!

first attempt at fuzzer fixes
